// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: file.proto

package br.ufu.facom.gbc074.project;

public final class File {
  private File() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_project_Client_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_project_Client_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_project_Product_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_project_Product_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_project_Order_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_project_Order_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_project_Reply_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_project_Reply_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_project_ID_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_project_ID_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\nfile.proto\022\007project\"#\n\006Client\022\013\n\003CID\030\001" +
      " \001(\t\022\014\n\004data\030\002 \001(\t\"$\n\007Product\022\013\n\003PID\030\001 \001" +
      "(\t\022\014\n\004data\030\002 \001(\t\"/\n\005Order\022\013\n\003OID\030\001 \001(\t\022\013" +
      "\n\003CID\030\002 \001(\t\022\014\n\004data\030\003 \001(\t\"@\n\005Reply\022\r\n\005er" +
      "ror\030\001 \001(\005\022\030\n\013description\030\002 \001(\tH\000\210\001\001B\016\n\014_" +
      "description\"\020\n\002ID\022\n\n\002ID\030\001 \001(\t2\242\003\n\013AdminP" +
      "ortal\0221\n\014CreateClient\022\017.project.Client\032\016" +
      ".project.Reply\"\000\0220\n\016RetrieveClient\022\013.pro" +
      "ject.ID\032\017.project.Client\"\000\0221\n\014UpdateClie" +
      "nt\022\017.project.Client\032\016.project.Reply\"\000\022-\n" +
      "\014DeleteClient\022\013.project.ID\032\016.project.Rep" +
      "ly\"\000\0223\n\rCreateProduct\022\020.project.Product\032" +
      "\016.project.Reply\"\000\0222\n\017RetrieveProduct\022\013.p" +
      "roject.ID\032\020.project.Product\"\000\0223\n\rUpdateP" +
      "roduct\022\020.project.Product\032\016.project.Reply" +
      "\"\000\022.\n\rDeleteProduct\022\013.project.ID\032\016.proje" +
      "ct.Reply\"\0002\206\002\n\013OrderPortal\022/\n\013CreateOrde" +
      "r\022\016.project.Order\032\016.project.Reply\"\000\022.\n\rR" +
      "etrieveOrder\022\013.project.ID\032\016.project.Orde" +
      "r\"\000\022/\n\013UpdateOrder\022\016.project.Order\032\016.pro" +
      "ject.Reply\"\000\022,\n\013DeleteOrder\022\013.project.ID" +
      "\032\016.project.Reply\"\000\0227\n\024RetrieveClientOrde" +
      "rs\022\013.project.ID\032\016.project.Order\"\0000\001B\037\n\033b" +
      "r.ufu.facom.gbc074.projectP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_project_Client_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_project_Client_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_project_Client_descriptor,
        new java.lang.String[] { "CID", "Data", });
    internal_static_project_Product_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_project_Product_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_project_Product_descriptor,
        new java.lang.String[] { "PID", "Data", });
    internal_static_project_Order_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_project_Order_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_project_Order_descriptor,
        new java.lang.String[] { "OID", "CID", "Data", });
    internal_static_project_Reply_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_project_Reply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_project_Reply_descriptor,
        new java.lang.String[] { "Error", "Description", "Description", });
    internal_static_project_ID_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_project_ID_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_project_ID_descriptor,
        new java.lang.String[] { "ID", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
