// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: file.proto

package br.ufu.facom.gbc074.project;

public interface IDOrBuilder extends
    // @@protoc_insertion_point(interface_extends:project.ID)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * generic ID for CID, PID and OID
   * </pre>
   *
   * <code>string ID = 1;</code>
   * @return The iD.
   */
  java.lang.String getID();
  /**
   * <pre>
   * generic ID for CID, PID and OID
   * </pre>
   *
   * <code>string ID = 1;</code>
   * @return The bytes for iD.
   */
  com.google.protobuf.ByteString
      getIDBytes();
}
