// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: file.proto

package br.ufu.facom.gbc074.project;

public interface OrderOrBuilder extends
    // @@protoc_insertion_point(interface_extends:project.Order)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Order ID
   * </pre>
   *
   * <code>string OID = 1;</code>
   * @return The oID.
   */
  java.lang.String getOID();
  /**
   * <pre>
   * Order ID
   * </pre>
   *
   * <code>string OID = 1;</code>
   * @return The bytes for oID.
   */
  com.google.protobuf.ByteString
      getOIDBytes();

  /**
   * <pre>
   * CLient ID
   * </pre>
   *
   * <code>string CID = 2;</code>
   * @return The cID.
   */
  java.lang.String getCID();
  /**
   * <pre>
   * CLient ID
   * </pre>
   *
   * <code>string CID = 2;</code>
   * @return The bytes for cID.
   */
  com.google.protobuf.ByteString
      getCIDBytes();

  /**
   * <pre>
   * JSON string representing at least array of PIDs, prices, and quantities
   * </pre>
   *
   * <code>string data = 3;</code>
   * @return The data.
   */
  java.lang.String getData();
  /**
   * <pre>
   * JSON string representing at least array of PIDs, prices, and quantities
   * </pre>
   *
   * <code>string data = 3;</code>
   * @return The bytes for data.
   */
  com.google.protobuf.ByteString
      getDataBytes();
}
